=== jpcuencas/Proyecto-XML/Proyecto XML/Entregado/XML-ProyectoFinal/XML-ProyectoFinal/proyectoXML.dtd
<!-- DTD de un lenguaje XML (XHTML)-->

<!ELEMENT ruta (nombre, descripcion, color, anchura, coordenadas)>

<!ELEMENT nombre (#PCDATA)>

<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT color (#PCDATA)>
<!ELEMENT anchura (#PCDATA)>
<!ELEMENT coordenadas (latlon)*>

<!ELEMENT latlon (#PCDATA)>

=== jpcuencas/Proyecto-XML/Proyecto XML/Entregado/XML-ProyectoFinal/XML-ProyectoFinal/ruta.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE html SYSTEM "proyectoXML.dtd">
<?xml-stylesheet type="text/xsl" href="proyectoXML.xsl"?>
<ruta xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance&quot; xsi:noNamespaceSchemaLocation=&quot;proyectoXML.xsd">
<nombre>Alicante - Murcia&#13;</nombre>
<descripcion>Ruta entre Alicante - Murcia&#13;</descripcion>
<color>0000ffaa</color>
<anchura>4</anchura>
<coordenadas>
	<latlon>-0.12, 39.08</latlon>
	<latlon>-0.15, 38.56</latlon>
</coordenadas>
</ruta>

=== jpcuencas/Proyecto-XML/Proyecto XML/ruta.xml
<?xml version="1.0" encoding="utf-8" ?>
<?xml-stylesheet href="proyectoXML.xsl" type="text/xsl" ?>
<!DOCTYPE html SYSTEM "proyectoXML.dtd">

<ruta xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="proyectoXML.xsd">
	<nombre>Alicante - Murcia</nombre>
	<descripcion>Ruta entre Alicante y Murcia</descripcion>
	<color>0000ffaa</color>
	<anchura>4</anchura>
	<coordenadas>
		<latlon>39.08, -0.12</latlon>
		<latlon>38.56, -0.15</latlon>
	</coordenadas>
</ruta>
